python:
  - 3.9
  - 3.10
  - 3.11
numpy:
  - 1.24
  - 1.24
  - 1.24
python_impl:
  - cpython
  - cpython
  - cpython
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 11.3                   # [osx and x86_64]
c_compiler:    # [win]
- vs2019       # [win]
cxx_compiler:  # [win]
- vs2019       # [win]
