python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12
numpy:
  - 1.26
  - 1.26
  - 1.26
  - 1.26
python_impl:
  - cpython
  - cpython
  - cpython
  - cpython
c_stdlib_version:          # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 11.3                   # [osx and x86_64]
c_compiler:    # [win]
- vs2019       # [win]
cxx_compiler:  # [win]
- vs2019       # [win]

