{% set name = "nionui-tool" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nion-software/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7451de007bc4229f5754ed4e5531014c7acaf2253365a94d9ebcda15288519f5
  patches:
    - patches/0001-Do-not-build-fat-binary.patch

build:
  number: 0
  skip: true  # [py<311]
  entry_points:
    - nionui-tool = nion.nionui_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt6-main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - chrpath  # [linux]
    - cmake
    - make  # [not win]
    - python                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - qt6-main                              # [build_platform != target_platform]
  host:
    - python
    - qt6-main
    - packaging
    - pip
    - setuptools
    - wheel
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt6-main

test:
  source_files:
    - nionui_app_test
  requires:
    - pip
    - nionui
    - numpy
    - scipy
    - h5py
  commands:
    - test -f "$PREFIX/bin/nionui-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/MacOS/Nion UI Launcher"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionui-tool"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/NionUILauncher"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionui-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\NionUILauncher.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\bootstrap.py" exit 1  # [win]
    - python -m pip install nionui_app_test/
    - nionui nionui_app.test_ack | grep ACK  # [osx]
    - nionui nionui_app.test_ack | findstr /c:"ACK"  # [win]
    # xvfb-run hangs on linux, so we need to run it in the background. probably due to something with SIGUSR1 signal.
    - xvfb-run -a nionui nionui_app.test_ack > ack.txt &  # [linux]
    - sleep 30  # [linux]
    - cat ack.txt | grep ACK  # [linux]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion UI apps.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
