{% set name = "nionui-tool" %}
{% set version = "0.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nion-software/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 54afb7195436744b612d4889465993a5605a4e1ea9e0f0f494087e9184a2319e
  patches:
    - patches/0001-Do-not-build-fat-binary.patch

build:
  number: 0
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - nionui-tool = nion.nionui_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt6-main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - chrpath  # [linux]
    - cmake
    - make  # [not win]
    - python                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy 1.22.*                          # [build_platform != target_platform]
    - qt6-main >=6.4.0,<7.0.0               # [build_platform != target_platform]
  host:
    - python
    - numpy 1.22.*
    - qt6-main >=6.4.0,<7.0.0
    - packaging
    - pip
    - setuptools
    - wheel
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt6-main >=6.4.0,<7.0.0
    - numpy >=1.21,<2.0

test:
  source_files:
    - nionui_app_test
  requires:
    - pip
    - nionui
    - numpy
    - scipy
    - h5py
  commands:
    - test -f "$PREFIX/bin/nionui-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/MacOS/Nion UI Launcher"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionui-tool"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/NionUILauncher"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionui-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\NionUILauncher.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\bootstrap.py" exit 1  # [win]
    - /usr/bin/sudo -n yum install -y xorg-x11-server-Xvfb  # [linux]
    - python -m pip install nionui_app_test/
    - nionui nionui_app.test_ack | grep ACK  # [osx]
    - nionui nionui_app.test_ack | findstr /c:"ACK"  # [win]
    - xvfb-run nionui nionui_app.test_ack | grep ACK  # [linux]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion UI apps.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
